### ISSUE TITLE
edev-ddd-support: mvn clean install: Test fail

### ISSUE THREAD

**Issue by BTMTimor** [mooodo/edev-ddd-monolith#1]
麻烦老师把表结构和数据同步一下哈

1. 字段名未同步，t_order的status字段已改为flag？
`
[ERROR] Tests run: 3, Failures: 0, Errors: 3, Skipped: 0, Time elapsed: 0.85 s <<< FAILURE! - in com.edev.support.dao.BasicDaoTest
[ERROR] testSaveAndDelete(com.edev.support.dao.BasicDaoTest)  Time elapsed: 0.83 s  <<< ERROR!
org.springframework.jdbc.BadSqlGrammarException: 

### Cause: java.sql.SQLSyntaxErrorException: Unknown column 'status' in 'field list'
; bad SQL grammar []; nested exception is java.sql.SQLSyntaxErrorException: Unknown column 'status' in 'field list'
	at com.edev.support.dao.BasicDaoTest.testSaveAndDelete(BasicDaoTest.java:31)
Caused by: java.sql.SQLSyntaxErrorException: Unknown column 'status' in 'field list'
	at com.edev.support.dao.BasicDaoTest.testSaveAndDelete(BasicDaoTest.java:31)
`

2. Order对象缺flag属性（或者修改下支持自动裁剪？）
`
[ERROR] testQueryOrderForDdd(com.edev.support.dao.QueryDaoTest)  Time elapsed: 0.006 s  <<< ERROR!
com.edev.support.exception.OrmException: No such field[flag] in the class[class com.edev.trade.order.entity.Order]
	at com.edev.support.dao.QueryDaoTest.testQueryOrderForDdd(QueryDaoTest.java:65)
`

**Comment by mooodo** [comment]
访问我在gitee的仓库，我主要在维护那边，这边更新没那么及时
https://gitee.com/mooodo/edev-ddd-monolith

**Comment by BTMTimor** [comment]
> 访问我在gitee的仓库，我主要在维护那边，这边更新没那么及时 https://gitee.com/mooodo/edev-ddd-monolith

好的
